window.TOEIC_VOCAB_LEXICON = {
  additional: { pos: "adj.", kk: "/əˈdɪʃənəl/", zh: "額外的；附加的" },
  adjust: { pos: "v.", kk: "/əˈdʒʌst/", zh: "調整；適應" },
  analyst: { pos: "n.", kk: "/ˈænəlɪst/", zh: "分析師" },
  announce: { pos: "v.", kk: "/əˈnaʊns/", zh: "宣布；公告" },
  announcement: { pos: "n.", kk: "/əˈnaʊnsmənt/", zh: "公告；宣布" },
  applicant: { pos: "n.", kk: "/ˈæpləkənt/", zh: "申請者；應徵者" },
  application: { pos: "n.", kk: "/ˌæpləˈkeʃən/", zh: "申請；申請表；應用程式" },
  arrange: { pos: "v.", kk: "/əˈrendʒ/", zh: "安排；整理" },
  arrangement: { pos: "n.", kk: "/əˈrendʒmənt/", zh: "安排；協議" },
  arrive: { pos: "v.", kk: "/əˈraɪv/", zh: "抵達；到達" },
  arrival: { pos: "n.", kk: "/əˈraɪvəl/", zh: "抵達；到貨" },
  assistant: { pos: "n.", kk: "/əˈsɪstənt/", zh: "助理" },
  attend: { pos: "v.", kk: "/əˈtɛnd/", zh: "出席；參加" },
  available: { pos: "adj.", kk: "/əˈveləbəl/", zh: "可取得的；有空的" },
  badge: { pos: "n.", kk: "/bædʒ/", zh: "識別證；徽章" },
  bidder: { pos: "n.", kk: "/ˈbɪdɚ/", zh: "投標者；出價者" },
  bidding: { pos: "n.", kk: "/ˈbɪdɪŋ/", zh: "投標；競標" },
  branch: { pos: "n.", kk: "/bræntʃ/", zh: "分行；分部" },
  brochure: { pos: "n.", kk: "/broˈʃʊr/", zh: "宣傳冊；小冊子" },
  budget: { pos: "n.", kk: "/ˈbʌdʒɪt/", zh: "預算" },
  cafeteria: { pos: "n.", kk: "/ˌkæfəˈtɪriə/", zh: "自助餐廳；員工餐廳" },
  candidate: { pos: "n.", kk: "/ˈkændəˌdet/", zh: "候選人；應徵者" },
  capacity: { pos: "n.", kk: "/kəˈpæsəti/", zh: "容量；能力" },
  catalog: { pos: "n.", kk: "/ˈkætəlɔg/", zh: "型錄；目錄" },
  client: { pos: "n.", kk: "/ˈklaɪənt/", zh: "客戶；委託人" },
  colleague: { pos: "n.", kk: "/ˈkɑlig/", zh: "同事" },
  complimentary: { pos: "adj.", kk: "/ˌkɑmpləˈmɛntəri/", zh: "免費贈送的；稱讚的" },
  conference: { pos: "n.", kk: "/ˈkɑnfərəns/", zh: "會議；研討會" },
  confirm: { pos: "v.", kk: "/kənˈfɝm/", zh: "確認；證實" },
  consultant: { pos: "n.", kk: "/kənˈsʌltənt/", zh: "顧問" },
  contact: { pos: "v./n.", kk: "/ˈkɑntækt/", zh: "聯絡；聯絡人" },
  contractor: { pos: "n.", kk: "/ˈkɑnˌtræktɚ/", zh: "承包商；約聘人員" },
  construction: { pos: "n.", kk: "/kənˈstrʌkʃən/", zh: "施工；建造" },
  customer: { pos: "n.", kk: "/ˈkʌstəmɚ/", zh: "顧客；客戶" },
  damage: { pos: "n./v.", kk: "/ˈdæmɪdʒ/", zh: "損害；損壞" },
  damaged: { pos: "adj.", kk: "/ˈdæmɪdʒd/", zh: "受損的；損壞的" },
  delay: { pos: "n./v.", kk: "/dɪˈle/", zh: "延誤；延遲" },
  deliver: { pos: "v.", kk: "/dɪˈlɪvɚ/", zh: "遞送；交付" },
  delivery: { pos: "n.", kk: "/dɪˈlɪvəri/", zh: "遞送；交貨" },
  department: { pos: "n.", kk: "/dɪˈpɑrtmənt/", zh: "部門；科系" },
  detailed: { pos: "adj.", kk: "/dɪˈteld/", zh: "詳細的" },
  discount: { pos: "n./v.", kk: "/ˈdɪskaʊnt/", zh: "折扣；打折" },
  display: { pos: "n./v.", kk: "/dɪˈsple/", zh: "展示；顯示" },
  disruption: { pos: "n.", kk: "/dɪsˈrʌpʃən/", zh: "中斷；干擾" },
  district: { pos: "n.", kk: "/ˈdɪstrɪkt/", zh: "區域；地區" },
  downtown: { pos: "adj./adv.", kk: "/ˈdaʊnˈtaʊn/", zh: "市中心的；在市中心" },
  employee: { pos: "n.", kk: "/ɪmˈplɔɪi/", zh: "員工；雇員" },
  employer: { pos: "n.", kk: "/ɪmˈplɔɪɚ/", zh: "雇主" },
  equipment: { pos: "n.", kk: "/ɪˈkwɪpmənt/", zh: "設備；器材" },
  estimate: { pos: "n./v.", kk: "/ˈɛstəˌmet/", zh: "估計；估價" },
  event: { pos: "n.", kk: "/ɪˈvɛnt/", zh: "活動；事件" },
  executive: { pos: "n./adj.", kk: "/ɪgˈzɛkjətɪv/", zh: "主管；行政的" },
  facility: { pos: "n.", kk: "/fəˈsɪləti/", zh: "設施；場所" },
  figure: { pos: "n.", kk: "/ˈfɪgjɚ/", zh: "數字；圖表；人物" },
  financial: { pos: "adj.", kk: "/faɪˈnænʃəl/", zh: "財務的；金融的" },
  flight: { pos: "n.", kk: "/flaɪt/", zh: "航班；飛行" },
  forecast: { pos: "n./v.", kk: "/ˈfɔrˌkæst/", zh: "預測；預報" },
  form: { pos: "n.", kk: "/fɔrm/", zh: "表格；形式" },
  forward: { pos: "v./adv.", kk: "/ˈfɔrwɚd/", zh: "轉寄；向前" },
  headquarters: { pos: "n.", kk: "/ˈhɛdˌkwɔrtɚz/", zh: "總部" },
  human: { pos: "adj.", kk: "/ˈhjumən/", zh: "人的；人力的" },
  illuminate: { pos: "v.", kk: "/ɪˈluməˌnet/", zh: "照亮；說明" },
  illuminated: { pos: "adj.", kk: "/ɪˈluməˌnetɪd/", zh: "照明的；發亮的" },
  impose: { pos: "v.", kk: "/ɪmˈpoz/", zh: "施加；強制實施" },
  improve: { pos: "v.", kk: "/ɪmˈpruv/", zh: "改善；提升" },
  include: { pos: "v.", kk: "/ɪnˈklud/", zh: "包含；包括" },
  inquiry: { pos: "n.", kk: "/ˈɪnkwəri/", zh: "詢問；查詢" },
  inspect: { pos: "v.", kk: "/ɪnˈspɛkt/", zh: "檢查；視察" },
  inspection: { pos: "n.", kk: "/ɪnˈspɛkʃən/", zh: "檢查；視察" },
  install: { pos: "v.", kk: "/ɪnˈstɔl/", zh: "安裝" },
  installation: { pos: "n.", kk: "/ˌɪnstəˈleʃən/", zh: "安裝；裝置" },
  instructor: { pos: "n.", kk: "/ɪnˈstrʌktɚ/", zh: "講師；教練" },
  inventory: { pos: "n.", kk: "/ˈɪnvənˌtɔri/", zh: "庫存；存貨清單" },
  invoice: { pos: "n.", kk: "/ˈɪnvɔɪs/", zh: "發票；帳單" },
  issue: { pos: "n./v.", kk: "/ˈɪʃu/", zh: "問題；發行；核發" },
  lease: { pos: "n./v.", kk: "/lis/", zh: "租約；租賃" },
  lobby: { pos: "n.", kk: "/ˈlɑbi/", zh: "大廳；門廳" },
  manual: { pos: "n./adj.", kk: "/ˈmænjuəl/", zh: "手冊；手動的" },
  manufacturer: { pos: "n.", kk: "/ˌmænjəˈfæktʃərɚ/", zh: "製造商" },
  meeting: { pos: "n.", kk: "/ˈmitɪŋ/", zh: "會議" },
  membership: { pos: "n.", kk: "/ˈmɛmbɚˌʃɪp/", zh: "會員資格" },
  notify: { pos: "v.", kk: "/ˈnotəˌfaɪ/", zh: "通知" },
  office: { pos: "n.", kk: "/ˈɔfɪs/", zh: "辦公室；事務所" },
  operation: { pos: "n.", kk: "/ˌɑpəˈreʃən/", zh: "營運；作業" },
  outcome: { pos: "n.", kk: "/ˈaʊtˌkʌm/", zh: "結果；成果" },
  participant: { pos: "n.", kk: "/pɑrˈtɪsəpənt/", zh: "參與者" },
  payment: { pos: "n.", kk: "/ˈpemənt/", zh: "付款；款項" },
  portal: { pos: "n.", kk: "/ˈpɔrtəl/", zh: "入口網站；門戶" },
  postpone: { pos: "v.", kk: "/poˈspon/", zh: "延期；延後" },
  previous: { pos: "adj.", kk: "/ˈpriviəs/", zh: "先前的；上一個的" },
  process: { pos: "n./v.", kk: "/ˈprɑsɛs/", zh: "流程；處理" },
  procurement: { pos: "n.", kk: "/prəˈkjʊrmənt/", zh: "採購；取得" },
  product: { pos: "n.", kk: "/ˈprɑdəkt/", zh: "產品" },
  purchase: { pos: "n./v.", kk: "/ˈpɝtʃəs/", zh: "購買；採購" },
  quarterly: { pos: "adj./adv.", kk: "/ˈkwɔrtɚli/", zh: "每季的；按季度地" },
  receipt: { pos: "n.", kk: "/rɪˈsit/", zh: "收據；收到" },
  reception: { pos: "n.", kk: "/rɪˈsɛpʃən/", zh: "接待處；招待會" },
  recommend: { pos: "v.", kk: "/ˌrɛkəˈmɛnd/", zh: "建議；推薦" },
  record: { pos: "n./v.", kk: "/ˈrɛkɚd/", zh: "紀錄；記錄" },
  register: { pos: "n./v.", kk: "/ˈrɛdʒɪstɚ/", zh: "收銀機；登記" },
  reimburse: { pos: "v.", kk: "/ˌriɪmˈbɝs/", zh: "報銷；償還" },
  reimbursement: { pos: "n.", kk: "/ˌriɪmˈbɝsmənt/", zh: "報銷；償付款" },
  release: { pos: "v./n.", kk: "/rɪˈlis/", zh: "發布；釋出" },
  relocate: { pos: "v.", kk: "/riˈloˌket/", zh: "搬遷；調職" },
  replacement: { pos: "n.", kk: "/rɪˈplesmənt/", zh: "替換品；更換" },
  representative: { pos: "n.", kk: "/ˌrɛprɪˈzɛntətɪv/", zh: "代表；業務人員" },
  request: { pos: "n./v.", kk: "/rɪˈkwɛst/", zh: "要求；請求" },
  reservation: { pos: "n.", kk: "/ˌrɛzɚˈveʃən/", zh: "預訂；保留" },
  response: { pos: "n.", kk: "/rɪˈspɑns/", zh: "回覆；反應" },
  restriction: { pos: "n.", kk: "/rɪˈstrɪkʃən/", zh: "限制；規定" },
  revise: { pos: "v.", kk: "/rɪˈvaɪz/", zh: "修訂；修改" },
  revised: { pos: "adj.", kk: "/rɪˈvaɪzd/", zh: "修訂過的" },
  schedule: { pos: "n./v.", kk: "/ˈskɛdʒul/", zh: "時程；安排" },
  seminar: { pos: "n.", kk: "/ˈsɛməˌnɑr/", zh: "研討會；講座" },
  service: { pos: "n.", kk: "/ˈsɝvɪs/", zh: "服務" },
  shipment: { pos: "n.", kk: "/ˈʃɪpmənt/", zh: "貨運；出貨" },
  shipping: { pos: "n./adj.", kk: "/ˈʃɪpɪŋ/", zh: "運送；運輸的" },
  shuttle: { pos: "n.", kk: "/ˈʃʌtəl/", zh: "接駁車；往返班車" },
  sign: { pos: "n./v.", kk: "/saɪn/", zh: "招牌；標誌；簽署" },
  software: { pos: "n.", kk: "/ˈsɔftˌwɛr/", zh: "軟體" },
  staff: { pos: "n.", kk: "/stæf/", zh: "員工；職員" },
  submit: { pos: "v.", kk: "/səbˈmɪt/", zh: "提交；呈交" },
  supplier: { pos: "n.", kk: "/səˈplaɪɚ/", zh: "供應商" },
  supply: { pos: "n./v.", kk: "/səˈplaɪ/", zh: "供應；用品" },
  survey: { pos: "n./v.", kk: "/ˈsɝve/", zh: "調查；問卷" },
  technician: { pos: "n.", kk: "/tɛkˈnɪʃən/", zh: "技術人員" },
  technology: { pos: "n.", kk: "/tɛkˈnɑlədʒi/", zh: "科技；技術" },
  tenant: { pos: "n.", kk: "/ˈtɛnənt/", zh: "房客；承租人" },
  training: { pos: "n.", kk: "/ˈtrenɪŋ/", zh: "訓練；培訓" },
  vendor: { pos: "n.", kk: "/ˈvɛndɚ/", zh: "供應商；賣方" },
  visitor: { pos: "n.", kk: "/ˈvɪzətɚ/", zh: "訪客；參觀者" },
  voucher: { pos: "n.", kk: "/ˈvaʊtʃɚ/", zh: "兌換券；憑證" },
  warehouse: { pos: "n.", kk: "/ˈwɛrˌhaʊs/", zh: "倉庫" },
  warranty: { pos: "n.", kk: "/ˈwɔrənti/", zh: "保固；保證書" },
  workshop: { pos: "n.", kk: "/ˈwɝkˌʃɑp/", zh: "工作坊；研習會" }
  , accommodate: { pos: "v.", kk: "/əˈkɑməˌdet/", zh: "容納；提供住宿；配合", example: "The hotel can accommodate up to two hundred conference guests." },
  account: { pos: "n./v.", kk: "/əˈkaʊnt/", zh: "帳戶；說明；占比", example: "Please update the billing account before Friday." },
  accurate: { pos: "adj.", kk: "/ˈækjərət/", zh: "準確的", example: "The report must include accurate sales figures." },
  accurately: { pos: "adv.", kk: "/ˈækjərətli/", zh: "準確地", example: "The sensor readings were not accurately recorded overnight." },
  accessible: { pos: "adj.", kk: "/ækˈsɛsəbəl/", zh: "可使用的；易取得的；無障礙的", example: "Captions make the webinar accessible to more participants." },
  achievement: { pos: "n.", kk: "/əˈtʃivmənt/", zh: "成就；達成", example: "The manager praised the team's achievement during the quarterly meeting." },
  agreement: { pos: "n.", kk: "/əˈgrimənt/", zh: "協議；合約；同意", example: "The legal department will review the vendor agreement." },
  analytics: { pos: "n.", kk: "/ˌænəˈlɪtɪks/", zh: "分析資料；分析工具", example: "The analytics dashboard updates after the sales data is uploaded." },
  archive: { pos: "v./n.", kk: "/ˈɑrˌkaɪv/", zh: "封存；檔案庫", example: "Please archive the completed support tickets." },
  assistance: { pos: "n.", kk: "/əˈsɪstəns/", zh: "協助；援助", example: "Contact the service desk if you need technical assistance." },
  attendee: { pos: "n.", kk: "/əˌtɛnˈdi/", zh: "與會者；出席者", example: "Each attendee received a digital ticket before the seminar." },
  automatic: { pos: "adj.", kk: "/ˌɔtəˈmætɪk/", zh: "自動的", example: "The automatic doors near the lobby are being repaired." },
  automatically: { pos: "adv.", kk: "/ˌɔtəˈmætɪkli/", zh: "自動地", example: "The dashboard automatically refreshes every hour." },
  automation: { pos: "n.", kk: "/ˌɔtəˈmeʃən/", zh: "自動化", example: "Automation reduced the time needed to process invoices." },
  beverage: { pos: "n.", kk: "/ˈbɛvərɪdʒ/", zh: "飲料", example: "Complimentary beverages will be served during the workshop." },
  caption: { pos: "n.", kk: "/ˈkæpʃən/", zh: "字幕；圖說", example: "The webinar caption appeared a few seconds late." },
  chatbot: { pos: "n.", kk: "/ˈtʃætˌbɑt/", zh: "聊天機器人", example: "The chatbot answers routine customer questions after hours." },
  check: { pos: "v./n.", kk: "/tʃɛk/", zh: "檢查；確認；支票", example: "Let me check the consultant's schedule." },
  code: { pos: "n.", kk: "/kod/", zh: "代碼；密碼；程式碼", example: "Scan the QR code on your ticket to check in." },
  compliance: { pos: "n.", kk: "/kəmˈplaɪəns/", zh: "法規遵循；合規", example: "The compliance team updated the data-retention policy." },
  dashboard: { pos: "n.", kk: "/ˈdæʃˌbɔrd/", zh: "儀表板；資訊面板", example: "The analytics dashboard shows weekly sales trends." },
  data: { pos: "n.", kk: "/ˈdetə/", zh: "資料；數據", example: "The sales data was uploaded to the client portal." },
  deadline: { pos: "n.", kk: "/ˈdɛdˌlaɪn/", zh: "截止期限", example: "The project deadline was moved to next Wednesday." },
  demo: { pos: "n.", kk: "/ˈdɛmo/", zh: "示範；展示", example: "The product demo will begin after the rehearsal." },
  departure: { pos: "n.", kk: "/dɪˈpɑrtʃɚ/", zh: "出發；離開", example: "Guests should arrive five minutes before departure." },
  displayed: { pos: "adj./v.", kk: "/dɪˈspled/", zh: "顯示的；展示了", example: "A confirmation message is displayed after the password is reset." },
  draft: { pos: "n./v.", kk: "/dræft/", zh: "草稿；起草", example: "Only the final draft needs legal approval." },
  elevator: { pos: "n.", kk: "/ˈɛləˌvetɚ/", zh: "電梯", example: "The elevator near the east entrance is out of service." },
  efficiently: { pos: "adv.", kk: "/ɪˈfɪʃəntli/", zh: "有效率地", example: "The template helps employees create reports more efficiently." },
  expense: { pos: "n.", kk: "/ɪkˈspɛns/", zh: "費用；支出", example: "Employees must submit expense reports by Friday." },
  final: { pos: "adj./n.", kk: "/ˈfaɪnəl/", zh: "最後的；最終版本", example: "The final version will be sent to all clients." },
  filter: { pos: "n./v.", kk: "/ˈfɪltɚ/", zh: "篩選器；過濾", example: "Use the history filter to find last month's records." },
  guest: { pos: "n.", kk: "/gɛst/", zh: "客人；賓客", example: "Hotel guests should follow the blue signs through the lobby." },
  history: { pos: "n.", kk: "/ˈhɪstəri/", zh: "歷史；紀錄", example: "The history page stores recent practice results." },
  kiosk: { pos: "n.", kk: "/ˈkiˌɑsk/", zh: "自助服務機；亭子", example: "Conference attendees may check in at the kiosk." },
  laboratory: { pos: "n.", kk: "/ˈlæbrəˌtɔri/", zh: "實驗室", example: "The laboratory purchased equipment for battery testing." },
  legal: { pos: "adj.", kk: "/ˈligəl/", zh: "法律的；法務的", example: "The legal department will review the agreement before upload." },
  luggage: { pos: "n.", kk: "/ˈlʌgɪdʒ/", zh: "行李", example: "Staff members will assist guests with luggage." },
  mobile: { pos: "adj.", kk: "/ˈmobəl/", zh: "行動的；手機的", example: "The mobile app displays a confirmation message." },
  overseas: { pos: "adj./adv.", kk: "/ˌovɚˈsiz/", zh: "海外的；在海外", example: "The webinar is open to overseas participants." },
  password: { pos: "n.", kk: "/ˈpæsˌwɝd/", zh: "密碼", example: "Customers can reset their password in the mobile app." },
  platform: { pos: "n.", kk: "/ˈplætˌfɔrm/", zh: "平台", example: "The streaming platform has a sync setting." },
  policy: { pos: "n.", kk: "/ˈpɑləsi/", zh: "政策；規定", example: "Vendors must sign the revised data-retention policy." },
  presentation: { pos: "n.", kk: "/ˌprɛzənˈteʃən/", zh: "簡報；發表", example: "The presentation was moved to a larger room." },
  presenter: { pos: "n.", kk: "/prɪˈzɛntɚ/", zh: "簡報者；主持人", example: "The presenter asked for a backup projector." },
  projector: { pos: "n.", kk: "/prəˈdʒɛktɚ/", zh: "投影機", example: "The projector in Conference Room C was too dark." },
  rehearsal: { pos: "n.", kk: "/rɪˈhɝsəl/", zh: "排練；彩排", example: "The team will run another rehearsal before the webinar." },
  retention: { pos: "n.", kk: "/rɪˈtɛnʃən/", zh: "保留；保存", example: "The policy explains the company's data-retention rules." },
  routine: { pos: "adj./n.", kk: "/ruˈtin/", zh: "例行的；慣例", example: "The chatbot handles routine questions after business hours." },
  security: { pos: "n.", kk: "/sɪˈkjʊrəti/", zh: "安全；保全", example: "Airport security rules were updated this morning." },
  sensor: { pos: "n.", kk: "/ˈsɛnsɚ/", zh: "感測器", example: "The sensor readings were not recorded accurately." },
  support: { pos: "n./v.", kk: "/səˈpɔrt/", zh: "支援；支持", example: "Archive the completed support tickets before closing the report." },
  sync: { pos: "n./v.", kk: "/sɪŋk/", zh: "同步", example: "Adjust the sync setting before the rehearsal." },
  tablet: { pos: "n.", kk: "/ˈtæblət/", zh: "平板電腦", example: "Someone restarted the tablet at the registration desk." },
  template: { pos: "n.", kk: "/ˈtɛmplət/", zh: "範本；模板", example: "Use the template to create expense reports." },
  ticket: { pos: "n.", kk: "/ˈtɪkɪt/", zh: "票券；工單", example: "Scan the QR code on your ticket to check in." },
  trouble: { pos: "n./v.", kk: "/ˈtrʌbəl/", zh: "麻煩；問題；使困擾", example: "Contact technical support if you have trouble uploading the file." },
  updated: { pos: "adj.", kk: "/ʌpˈdetɪd/", zh: "更新後的", example: "The updated invoice template is ready." },
  upload: { pos: "v./n.", kk: "/ˈʌpˌlod/", zh: "上傳", example: "Upload the report to the client portal by noon." },
  webinar: { pos: "n.", kk: "/ˈwɛbəˌnɑr/", zh: "網路研討會", example: "The webinar test looks clear, but the captions are delayed." }
};
